[toolchain]
anchor_version = "0.31.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_distributor = "ErbDoJTnJyG6EBXHeFochTsHJhB3Jfjc3MF1L9aNip3y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "test-wallet-1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
